name: Create Release - Unstable

on:
  workflow_dispatch:
    inputs:
      changelog:
        description: 'Changelog'
        required: true
        type: string

permissions:
  actions: read
  contents: write

jobs:
  create-release:
    name: Create unstable apworld
    runs-on: ubuntu-latest

    steps:
      - name: Set current date to env
        run: |
          echo "CURRENT_DATE=$(date +'%m%d%Y')" >> "$GITHUB_ENV"
          echo "CURRENT_DATE_TEXT=$(date +'%B %d, %Y')" >> "$GITHUB_ENV"
      - name: Set expected file basename to env
        run: echo "BASENAME=manual_unstable_${{ env.CURRENT_DATE }}" >> "$GITHUB_ENV"
      - name: Format changelog input as multiline string and put into env
        run: |
          echo 'CHANGELOG<<EOF' >> "$GITHUB_ENV"
          echo "This release contains the following changes:\n\n" >> "$GITHUB_ENV"
          echo "${{ github.event.inputs.changelog }}" >> "$GITHUB_ENV"
          echo 'EOF' >> "$GITHUB_ENV"
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Create apworld file
        # rename src folder, zip it, change extension
        run: |
          mv src ${{ env.BASENAME }}
          zip ${{ env.BASENAME }}.zip ${{ env.BASENAME }}/*
          mv ${{ env.BASENAME }}.zip ${{ env.BASENAME }}.apworld
      - name: Upload apworld as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BASENAME }}.apworld
          path: ${{ env.BASENAME }}.apworld
          if-no-files-found: error
      - name: Create an unstable release
        uses: ncipollo/release-action@v1
        with:
          name: "Unstable release - ${{ env.CURRENT_DATE_TEXT }}"
          body: ${{ env.CHANGELOG }}
          tag: ${{ env.BASENAME }}
          commit: main
          artifacts: "${{ env.BASENAME }}.apworld"
